#!/usr/bin/env bash

cat <<+++
SPOOL "${output}" REPLACE

WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

SET DEFINE OFF
SET AUTOCOMMIT OFF

SET TRIMOUT ON
SET TRIMSPOOL ON
SET TERMOUT OFF
SET ECHO OFF
SET FLUSH OFF
SET HEADING OFF
SET UNDERLINE OFF
SET NEWPAGE NONE
SET PAGESIZE 0
SET TIME OFF
SET TIMING OFF

SET LINESIZE ${linesize}
SET WRAP OFF

SET SQLBLANKLINES ON
SET COLSEP "${colsep}"
SET NULL "${null}"
SET SQLTERMINATOR ";"

SET FEEDBACK OFF
SET TAB OFF
SET VERIFY OFF

SET TRIMS ON
SET TRIMSPOOL ON
SET TRIMOUT ON

CONNECT ${logon};

ALTER SESSION
SET CURRENT_SCHEMA = "${DBSCHEMA}";

ALTER SESSION
SET NLS_DATE_FORMAT = 'YYYY-MM-DD';
+++
